"""add_archetype_is_custom

Revision ID: 1413b684d806
Revises: 6641aaaaee68
Create Date: 2026-04-14 01:46:11.408020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1413b684d806'
down_revision: Union[str, Sequence[str], None] = '6641aaaaee68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archetypes', sa.Column('is_custom', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archetypes', 'is_custom')
    # ### end Alembic commands ###
