"""add_archetype_meta_rank

Revision ID: 6641aaaaee68
Revises: 1292fad8bfd5
Create Date: 2026-04-14 01:37:21.942600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6641aaaaee68'
down_revision: Union[str, Sequence[str], None] = '1292fad8bfd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archetypes', sa.Column('meta_rank', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_archetypes_meta_rank'), 'archetypes', ['meta_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archetypes_meta_rank'), table_name='archetypes')
    op.drop_column('archetypes', 'meta_rank')
    # ### end Alembic commands ###
