"""Pure contracts, fixtures and generator for seasonal bingo board previews."""

from services.achievements.bingo.fixtures import (
    FIXTURE_CATALOG_VERSION,
    FIXTURE_DECK_STATS_SNAPSHOT_ID,
    FIXTURE_DECK_TARGETS,
    PREVIEW_MANIFESTS,
    FixturePersona,
    fixture_candidates,
)
from services.achievements.bingo.generator import BoardGenerationError, generate_board
from services.achievements.bingo.models import (
    ALGORITHM_VERSION,
    AchievementTypeManifest,
    BoardConstraints,
    BoardDraft,
    Category,
    DataSource,
    Difficulty,
    EligibilityResult,
    InstantiatedCandidate,
    ManifestStatus,
    Requirement,
)
from services.achievements.bingo.parameterizers import (
    PLAY_DECK_CODE,
    FrozenDeckTarget,
    instantiate_play_deck_candidates,
    play_deck_completed,
)
from services.achievements.bingo.play_deck_counter import (
    PLAY_DECK_COUNTER_COMPLETION_KEY,
    PLAY_DECK_COUNTER_MANIFEST_VERSION,
    PLAY_DECK_COUNTER_PARAMETERIZER_KEY,
    PLAY_DECK_COUNTER_PROGRESS_KEY,
    PLAY_DECK_TARGET_PARAM,
    PLAY_DECK_TARGET_TOURNAMENTS,
    PlayDeckCounterProgress,
    PlayDeckTournamentEvidence,
    build_play_deck_counter_manifest,
    evaluate_play_deck_counter,
    instantiate_play_deck_counter_candidates,
)

__all__ = [
    "ALGORITHM_VERSION",
    "FIXTURE_CATALOG_VERSION",
    "FIXTURE_DECK_STATS_SNAPSHOT_ID",
    "FIXTURE_DECK_TARGETS",
    "PLAY_DECK_CODE",
    "PLAY_DECK_COUNTER_COMPLETION_KEY",
    "PLAY_DECK_COUNTER_MANIFEST_VERSION",
    "PLAY_DECK_COUNTER_PARAMETERIZER_KEY",
    "PLAY_DECK_COUNTER_PROGRESS_KEY",
    "PLAY_DECK_TARGET_PARAM",
    "PLAY_DECK_TARGET_TOURNAMENTS",
    "PREVIEW_MANIFESTS",
    "AchievementTypeManifest",
    "BoardConstraints",
    "BoardDraft",
    "BoardGenerationError",
    "Category",
    "DataSource",
    "Difficulty",
    "EligibilityResult",
    "FixturePersona",
    "FrozenDeckTarget",
    "InstantiatedCandidate",
    "ManifestStatus",
    "PlayDeckCounterProgress",
    "PlayDeckTournamentEvidence",
    "Requirement",
    "build_play_deck_counter_manifest",
    "evaluate_play_deck_counter",
    "fixture_candidates",
    "generate_board",
    "instantiate_play_deck_candidates",
    "instantiate_play_deck_counter_candidates",
    "play_deck_completed",
]
